/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg360project;

import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tasos
 */
public class proslipseis extends javax.swing.JFrame {
DBConnect connect=new DBConnect();
String name;
String id;
Boolean combo_box;
    /**
     * Creates new form proslipseis
     */
    public proslipseis(String name) {
        initComponents();
        this.name=name;
        if(Fillcombo()){
        this.combo_box=true;        
        this.setVisible(true);
        }else{
            this.dispose();
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        add_lbl = new javax.swing.JLabel();
        phone_lbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        prof_lbl = new javax.swing.JLabel();
        lang_lbl = new javax.swing.JLabel();
        std_lbl = new javax.swing.JLabel();
        spec_lbl = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        st_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        spec_lbl.setText("specialties");

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        st_btn.setText("Πρόσληψη");
        st_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st_btnActionPerformed(evt);
            }
        });

        jButton1.setText("προβολή");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_lbl)
                                    .addComponent(phone_lbl)
                                    .addComponent(email_lbl))
                                .addGap(231, 231, 231)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(std_lbl)
                                    .addComponent(lang_lbl)
                                    .addComponent(spec_lbl)))
                            .addComponent(name_lbl)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(prof_lbl)
                                .addGap(5, 5, 5))))
                    .addComponent(st_btn)
                    .addComponent(jButton1))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_lbl)
                    .addComponent(prof_lbl)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lang_lbl)
                    .addComponent(add_lbl))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std_lbl)
                    .addComponent(phone_lbl))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_lbl)
                    .addComponent(spec_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(st_btn)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void st_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st_btnActionPerformed
        try{
        connect.proslipsh(this.name , combo.getSelectedItem().toString());
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_st_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.combo_box){
         String[] ind=connect.getIndividual(combo.getSelectedItem().toString());
        name_lbl.setText(ind[0]);
        add_lbl.setText(ind[1]);
        phone_lbl.setText(ind[2]);
        email_lbl.setText(ind[3]);
        prof_lbl.setText(ind[4]);
        
        if(ind[7].equals("0")){
            lang_lbl.setText("Καμία");
        }else if(ind[7].equals("1")){
            lang_lbl.setText("Αγγλικά");
        }else if(ind[7].equals("2")){
            lang_lbl.setText("Γερμανικά");
        }else{
            lang_lbl.setText("Αγγλικά,Γερμανικά");
        }
        
        std_lbl.setText(ind[8]);
        spec_lbl.setText(ind[9]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
private boolean Fillcombo(){
    try{
        String sql="select distinct user from matching where comp_name=? and status=0";
        PreparedStatement pst=connect.con.prepareStatement(sql);
        pst.setString(1, this.name);
        connect.rs=pst.executeQuery();
        if(connect.rs.next()){
        while(connect.rs.next()){
            String name=connect.rs.getString("user");
            
            
           combo.addItem(name);
           
        }
        return true;
        }else{
            JOptionPane.showMessageDialog(null, "Δεν υπάρχουν διαθέσιμοι ενδιαφερόμενοι αυτή τη στιγμή");
            this.dispose();
            return false;
        }
    }catch(Exception e){
        System.out.println("error"+e);
        return false;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_lbl;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lang_lbl;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel phone_lbl;
    private javax.swing.JLabel prof_lbl;
    private javax.swing.JLabel spec_lbl;
    private javax.swing.JButton st_btn;
    private javax.swing.JLabel std_lbl;
    // End of variables declaration//GEN-END:variables
}
